spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:inventorydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/master}
  cloud:
    bus:
      enabled: ${SPRING_CLOUD_BUS_ENABLED:false}
    stream:
      defaultBinder: rabbit

server:
  port: ${INVENTORY_SERVICE_PORT:8083}

logging:
  level:
    com.example.inventory: INFO
